# Generated by Django 2.2.2 on 2019-06-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('der', models.CharField(max_length=100, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.Comunidad')),
            ],
        ),
    ]
